import test from 'ava';

import parseDataset from './parseDataset';

test('parseDataset - returns one object regardless of dataset size', (t) => {
  const expected = {
    e: ['m', 'n', 'r', 's'],
    n: ['a', 'e', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 's', 't', 'u', 'z'],
    l: ['a', 'g', 'i', 'n'],
    i: ['a', 'd', 'g', 'k', 'l', 'n', 'r', 's'],
    a: ['b', 'd', 'g', 'h', 'k', 'l', 'm', 'n', 'r', 's', 't', 'u', 'z'],
    k: ['a', 'i', 'k', 'u'],
    u: ['b', 'e', 'g', 'k', 'l', 'm', 'n', 'r', 't', 'z'],
    t: ['a', 'i', 'u'],
    s: ['a', 'h', 'i', 't', 'u'],
    h: ['a', 'e', 'k', 't', 'u', 'z'],
    m: ['a', 'e', 'g', 'm', 'u'],
    z: ['i', 'u'],
    r: ['a', 'd', 'e', 'g', 'r', 's', 't'],
    g: ['a', 'e', 'g', 'i', 'o', 'u'],
    b: ['a', 'u', 'z'],
    d: ['a', 'u'],
    o: ['n'],
  };
  const actual = parseDataset([
    'enlil',
    'an',
    'enki',
    'utu',
    'shamash',
    'nanna',
    'enzu',
    'zuen',
    'suen',
    'sin',
    'nergal',
    'nabu',
    'marduk',
    'inanna',
    'ishatar',
    'ninurta',
    'ningirsu',
    'abzu',
    'anshar',
    'kishar',
    'ki',
    'nammu',
    'tiamat',
    'ashur',
    'dagan',
    'dagon',
    'dumuzid',
    'tammuz',
    'ereshkigal',
    'geshtinanna',
    'gilgamesh',
    'gula',
    'nintinugga',
    'ninkarrak',
    'meme',
    'bau',
    'ninisina',
    'ishkur',
    'adad',
    'istaran',
    'nanshe',
    'ninazu',
    'ningal',
    'nikkal',
    'ningishzida',
    'ninhursag',
    'damgalnuna',
    'ninmah',
    'ninlil',
    'ninshubur',
    'nisaba',
  ]);
  t.deepEqual(actual, expected);
});
